# Generated by Django 4.2.30 on 2026-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bacteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="菌種名稱"),
                ),
                (
                    "is_commensal",
                    models.BooleanField(default=False, verbose_name="常在菌"),
                ),
            ],
            options={
                "verbose_name": "菌種",
                "verbose_name_plural": "菌種",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exec_date", models.DateTimeField(db_index=True, verbose_name="執行時間")),
                (
                    "visit_no",
                    models.CharField(blank=True, max_length=32, verbose_name="就診序號"),
                ),
                (
                    "order_no",
                    models.CharField(blank=True, max_length=32, verbose_name="醫囑序號"),
                ),
                (
                    "item_no",
                    models.CharField(blank=True, max_length=32, verbose_name="項目序號"),
                ),
                (
                    "bacteria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="clinical.bacteria",
                        verbose_name="菌種",
                    ),
                ),
            ],
            options={
                "verbose_name": "臨床事件",
                "verbose_name_plural": "臨床事件",
                "ordering": ["exec_date"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=16, unique=True, verbose_name="科別代碼"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="科別名稱")),
            ],
            options={
                "verbose_name": "科別",
                "verbose_name_plural": "科別",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="類別代碼")),
                ("type_name", models.CharField(max_length=64, verbose_name="類別名稱")),
                (
                    "source",
                    models.CharField(blank=True, max_length=64, verbose_name="資料來源"),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("admission", "住院"),
                            ("nursing", "護理紀錄"),
                            ("tube", "導管"),
                            ("vital", "異常生理評值"),
                        ],
                        max_length=16,
                        verbose_name="事件分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "事件類別",
                "verbose_name_plural": "事件類別",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=16, unique=True, verbose_name="病房代碼"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="病房名稱")),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="clinical.division",
                        verbose_name="科別",
                    ),
                ),
            ],
            options={
                "verbose_name": "病房",
                "verbose_name_plural": "病房",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="體溫",
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=16, verbose_name="血壓"),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="脈搏"
                    ),
                ),
                (
                    "spo2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="血氧"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_sign",
                        to="clinical.clinicalevent",
                        verbose_name="臨床事件",
                    ),
                ),
            ],
            options={"verbose_name": "生理數值", "verbose_name_plural": "生理數值",},
        ),
        migrations.CreateModel(
            name="Tube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tube_no",
                    models.PositiveIntegerField(unique=True, verbose_name="導管編號"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="導管名稱")),
                (
                    "category",
                    models.IntegerField(
                        choices=[(1, "標準名稱"), (2, "待歸類（來源一）"), (3, "待歸類（來源二）")],
                        verbose_name="分類",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次數"),
                ),
                (
                    "canonical",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": 1},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="clinical.tube",
                        verbose_name="對應標準名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "導管",
                "verbose_name_plural": "導管",
                "ordering": ["tube_no"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_no",
                    models.CharField(
                        db_index=True, max_length=16, unique=True, verbose_name="病歷號"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性別",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="出生日期")),
                (
                    "ward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="clinical.ward",
                        verbose_name="目前病房",
                    ),
                ),
            ],
            options={
                "verbose_name": "病患",
                "verbose_name_plural": "病患",
                "ordering": ["chart_no"],
            },
        ),
        migrations.CreateModel(
            name="ExamReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_no",
                    models.CharField(db_index=True, max_length=32, verbose_name="報告編號"),
                ),
                ("exec_time", models.DateTimeField(verbose_name="報告時間")),
                ("content", models.TextField(verbose_name="報告內容")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="clinical.clinicalevent",
                        verbose_name="臨床事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "檢驗報告",
                "verbose_name_plural": "檢驗報告",
                "ordering": ["-exec_time"],
            },
        ),
        migrations.AddField(
            model_name="clinicalevent",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="clinical.division",
                verbose_name="科別",
            ),
        ),
        migrations.AddField(
            model_name="clinicalevent",
            name="med_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="clinical.medtype",
                verbose_name="事件類別",
            ),
        ),
        migrations.AddField(
            model_name="clinicalevent",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clinical.patient",
                verbose_name="病患",
            ),
        ),
        migrations.AddField(
            model_name="clinicalevent",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="clinical.ward",
                verbose_name="病房",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalevent",
            index=models.Index(
                fields=["patient", "exec_date"], name="clinical_cl_patient_f0b668_idx"
            ),
        ),
    ]
