# Generated by Django 4.2.30 on 2026-08-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CultureIsolate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "growth",
                    models.CharField(
                        choices=[
                            ("+", "少量 (+)"),
                            ("++", "中量 (++)"),
                            ("+++", "大量 (+++)"),
                        ],
                        default="++",
                        max_length=3,
                        verbose_name="生長量",
                    ),
                ),
                (
                    "colony_count",
                    models.CharField(blank=True, max_length=64, verbose_name="菌落數"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="isolates",
                        to="clinical.bacteria",
                        verbose_name="菌種",
                    ),
                ),
            ],
            options={
                "verbose_name": "培養菌株",
                "verbose_name_plural": "培養菌株",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="examreport",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="採檢時間"),
        ),
        migrations.AddField(
            model_name="examreport",
            name="kind",
            field=models.CharField(
                choices=[
                    ("culture", "微生物培養報告"),
                    ("nursing", "護理紀錄"),
                    ("vital", "生理評值紀錄"),
                ],
                default="culture",
                max_length=16,
                verbose_name="報告類型",
            ),
        ),
        migrations.AddField(
            model_name="examreport",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="簽收時間"),
        ),
        migrations.AddField(
            model_name="examreport",
            name="specimen",
            field=models.CharField(blank=True, max_length=128, verbose_name="檢驗來源"),
        ),
        migrations.AddField(
            model_name="examreport",
            name="test_name",
            field=models.CharField(blank=True, max_length=128, verbose_name="檢驗項目"),
        ),
        migrations.AlterField(
            model_name="examreport",
            name="content",
            field=models.TextField(blank=True, verbose_name="報告內容"),
        ),
        migrations.CreateModel(
            name="SusceptibilityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("antibiotic", models.CharField(max_length=128, verbose_name="抗生素")),
                (
                    "mic",
                    models.CharField(blank=True, max_length=32, verbose_name="MIC"),
                ),
                (
                    "interpretation",
                    models.CharField(
                        choices=[("S", "敏感 (S)"), ("I", "中等 (I)"), ("R", "抗藥 (R)")],
                        max_length=1,
                        verbose_name="判讀",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "isolate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="susceptibilities",
                        to="clinical.cultureisolate",
                        verbose_name="培養菌株",
                    ),
                ),
            ],
            options={
                "verbose_name": "抗生素敏感性",
                "verbose_name_plural": "抗生素敏感性",
                "ordering": ["order", "antibiotic"],
            },
        ),
        migrations.AddField(
            model_name="cultureisolate",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isolates",
                to="clinical.examreport",
                verbose_name="檢驗報告",
            ),
        ),
    ]
