# Generated by Django 4.2.30 on 2026-08-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_cultureisolate_examreport_collected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examreport",
            name="raw_text",
            field=models.TextField(blank=True, verbose_name="原始報告全文"),
        ),
    ]
