# Generated by Django 4.2.30 on 2026-08-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_examreport_raw_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(db_index=True, verbose_name="測量時間"),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="脈搏"
                    ),
                ),
                (
                    "respiration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="呼吸"
                    ),
                ),
                (
                    "spo2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="血氧"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="體溫",
                    ),
                ),
                (
                    "systolic",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="收縮壓"
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="舒張壓"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="clinical.clinicalevent",
                        verbose_name="來源紀錄",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="clinical.patient",
                        verbose_name="病患",
                    ),
                ),
            ],
            options={
                "verbose_name": "生命徵象量測",
                "verbose_name_plural": "生命徵象量測",
                "ordering": ["measured_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "measured_at"],
                        name="clinical_vi_patient_8d2b55_idx",
                    )
                ],
            },
        ),
    ]
