"""Core clinical records.

These replace the hand-written MSSQL tables the original site queried with raw
SQL (``I_Patient``, ``I_AllExam_Test0419``, ``medTypeSet``, ``TUBE`` …).  Every
row in the demo is fictional and generated by ``manage.py seed_demo``.
"""

from django.db import models


class Division(models.Model):
    """Hospital department, e.g. 內科 / 外科."""

    code = models.CharField('科別代碼', max_length=16, unique=True)
    name = models.CharField('科別名稱', max_length=64)

    class Meta:
        verbose_name = verbose_name_plural = '科別'
        ordering = ['code']

    def __str__(self):
        return self.name


class Ward(models.Model):
    """Inpatient ward.  ``locationnow`` in the original schema."""

    code = models.CharField('病房代碼', max_length=16, unique=True)
    name = models.CharField('病房名稱', max_length=64)
    division = models.ForeignKey(
        Division, on_delete=models.PROTECT, related_name='wards', verbose_name='科別'
    )

    class Meta:
        verbose_name = verbose_name_plural = '病房'
        ordering = ['code']

    def __str__(self):
        return f'{self.code} {self.name}'


class Patient(models.Model):
    """A fictional patient.  ``chart_no`` replaces the original ``ChartNo``."""

    class Gender(models.TextChoices):
        MALE = 'M', '男'
        FEMALE = 'F', '女'

    chart_no = models.CharField('病歷號', max_length=16, unique=True, db_index=True)
    name = models.CharField('姓名', max_length=32)
    gender = models.CharField('性別', max_length=1, choices=Gender.choices)
    birth_date = models.DateField('出生日期')
    ward = models.ForeignKey(
        Ward,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='patients',
        verbose_name='目前病房',
    )

    class Meta:
        verbose_name = verbose_name_plural = '病患'
        ordering = ['chart_no']

    def __str__(self):
        return f'{self.chart_no} {self.name}'

    @property
    def masked_name(self):
        """Name with the middle characters hidden, for de-identified views."""
        if len(self.name) <= 1:
            return self.name
        if len(self.name) == 2:
            return f'{self.name[0]}O'
        return f'{self.name[0]}{"O" * (len(self.name) - 2)}{self.name[-1]}'


class MedType(models.Model):
    """Event type lookup — the original ``medTypeSet`` table.

    ``code`` keeps the original numeric values (2131 = 入院, 30903 = 導管 …)
    because the front-end filters on them.
    """

    class Category(models.TextChoices):
        ADMISSION = 'admission', '住院'
        NURSING = 'nursing', '護理紀錄'
        TUBE = 'tube', '導管'
        VITAL = 'vital', '異常生理評值'

    code = models.IntegerField('類別代碼', unique=True)
    type_name = models.CharField('類別名稱', max_length=64)
    source = models.CharField('資料來源', max_length=64, blank=True)
    event_category = models.CharField(
        '事件分類', max_length=16, choices=Category.choices
    )

    class Meta:
        verbose_name = verbose_name_plural = '事件類別'
        ordering = ['code']

    def __str__(self):
        return f'{self.code} {self.type_name}'


class Bacteria(models.Model):
    """Organism lookup, used by the infection-control filters."""

    name = models.CharField('菌種名稱', max_length=128, unique=True)
    is_commensal = models.BooleanField('常在菌', default=False)

    class Meta:
        verbose_name = verbose_name_plural = '菌種'
        ordering = ['name']

    def __str__(self):
        return self.name


class ClinicalEvent(models.Model):
    """One row on a patient's timeline.

    Collapses the original ``I_AllExam_Test0419`` table plus the
    ``threedayprogression`` and ``bodycheck`` table-valued functions into a
    single typed model.
    """

    patient = models.ForeignKey(
        Patient, on_delete=models.CASCADE, related_name='events', verbose_name='病患'
    )
    med_type = models.ForeignKey(
        MedType, on_delete=models.PROTECT, related_name='events', verbose_name='事件類別'
    )
    exec_date = models.DateTimeField('執行時間', db_index=True)
    visit_no = models.CharField('就診序號', max_length=32, blank=True)
    order_no = models.CharField('醫囑序號', max_length=32, blank=True)
    item_no = models.CharField('項目序號', max_length=32, blank=True)
    ward = models.ForeignKey(
        Ward,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='events',
        verbose_name='病房',
    )
    division = models.ForeignKey(
        Division,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='events',
        verbose_name='科別',
    )
    bacteria = models.ForeignKey(
        Bacteria,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='events',
        verbose_name='菌種',
    )

    class Meta:
        verbose_name = verbose_name_plural = '臨床事件'
        ordering = ['exec_date']
        indexes = [models.Index(fields=['patient', 'exec_date'])]

    def __str__(self):
        return f'{self.patient.chart_no} {self.exec_date:%Y-%m-%d} {self.med_type.type_name}'


class VitalSign(models.Model):
    """Body temperature / blood pressure / pulse / SpO2 for one event."""

    event = models.OneToOneField(
        ClinicalEvent,
        on_delete=models.CASCADE,
        related_name='vital_sign',
        verbose_name='臨床事件',
    )
    temperature = models.DecimalField('體溫', max_digits=4, decimal_places=1, null=True, blank=True)
    blood_pressure = models.CharField('血壓', max_length=16, blank=True)
    pulse = models.PositiveIntegerField('脈搏', null=True, blank=True)
    spo2 = models.PositiveIntegerField('血氧', null=True, blank=True)

    class Meta:
        verbose_name = verbose_name_plural = '生理數值'

    def __str__(self):
        return f'{self.event_id} 生理數值'


class ExamReport(models.Model):
    """A report attached to an event (original ``AnalyseText``).

    Two shapes share this model, distinguished by :attr:`kind`:

    * ``CULTURE`` — a microbiology culture report: specimen, organism isolated,
      colony count, and a panel of :class:`SusceptibilityResult` rows.
    * ``NURSING`` / ``VITAL`` — a narrative note whose text is the report.
    """

    class Kind(models.TextChoices):
        CULTURE = 'culture', '微生物培養報告'
        NURSING = 'nursing', '護理紀錄'
        VITAL = 'vital', '生理評值紀錄'

    event = models.ForeignKey(
        ClinicalEvent,
        on_delete=models.CASCADE,
        related_name='reports',
        verbose_name='臨床事件',
    )
    kind = models.CharField(
        '報告類型', max_length=16, choices=Kind.choices, default=Kind.CULTURE
    )
    report_no = models.CharField('報告編號', max_length=32, db_index=True)
    exec_time = models.DateTimeField('報告時間')
    content = models.TextField('報告內容', blank=True)

    # The report exactly as the source system emits it: a plain-text dump with
    # its own header block and column alignment.  Everything else on this model
    # (and the isolate/susceptibility rows) is the parsed form of this text, so
    # a reviewer can always check the structured view against the original.
    raw_text = models.TextField('原始報告全文', blank=True)

    # Culture-report fields; left blank on narrative notes.
    test_name = models.CharField('檢驗項目', max_length=128, blank=True)
    specimen = models.CharField('檢驗來源', max_length=128, blank=True)
    collected_at = models.DateTimeField('採檢時間', null=True, blank=True)
    received_at = models.DateTimeField('簽收時間', null=True, blank=True)

    class Meta:
        verbose_name = verbose_name_plural = '檢驗報告'
        ordering = ['-exec_time']

    def __str__(self):
        return f'{self.report_no}'


class VitalMeasurement(models.Model):
    """One row of a patient's consolidated vital-sign chart.

    Readings are charted against the patient, not against whichever note
    happened to record them: the chart a reviewer reads is every measurement
    for that patient in time order, pulled together from all their records.
    ``event`` keeps the link back to the record a reading came from.

    Not every reading records every field — a nurse may chart only a
    temperature, or only a blood pressure — so all columns are nullable and
    render as blank cells.

    ``VitalSign`` remains the single summary reading shown on the timeline.
    """

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        related_name='measurements',
        verbose_name='病患',
    )
    event = models.ForeignKey(
        ClinicalEvent,
        on_delete=models.CASCADE,
        related_name='measurements',
        null=True,
        blank=True,
        verbose_name='來源紀錄',
    )
    measured_at = models.DateTimeField('測量時間', db_index=True)
    pulse = models.PositiveIntegerField('脈搏', null=True, blank=True)
    respiration = models.PositiveIntegerField('呼吸', null=True, blank=True)
    spo2 = models.PositiveIntegerField('血氧', null=True, blank=True)
    temperature = models.DecimalField(
        '體溫', max_digits=4, decimal_places=1, null=True, blank=True
    )
    systolic = models.PositiveIntegerField('收縮壓', null=True, blank=True)
    diastolic = models.PositiveIntegerField('舒張壓', null=True, blank=True)

    class Meta:
        verbose_name = verbose_name_plural = '生命徵象量測'
        ordering = ['measured_at']
        indexes = [models.Index(fields=['patient', 'measured_at'])]

    def __str__(self):
        return f'{self.patient.chart_no} {self.measured_at:%Y-%m-%d %H:%M}'


class CultureIsolate(models.Model):
    """One organism grown from a culture report.

    A single specimen often grows more than one organism, each with its own
    sensitivity panel, so isolates hang off the report rather than the report
    carrying a single ``organism`` field.
    """

    class Growth(models.TextChoices):
        LIGHT = '+', '少量 (+)'
        MODERATE = '++', '中量 (++)'
        HEAVY = '+++', '大量 (+++)'

    report = models.ForeignKey(
        ExamReport,
        on_delete=models.CASCADE,
        related_name='isolates',
        verbose_name='檢驗報告',
    )
    organism = models.ForeignKey(
        Bacteria,
        on_delete=models.PROTECT,
        related_name='isolates',
        verbose_name='菌種',
    )
    growth = models.CharField(
        '生長量', max_length=3, choices=Growth.choices, default=Growth.MODERATE
    )
    colony_count = models.CharField('菌落數', max_length=64, blank=True)
    order = models.PositiveIntegerField('排序', default=0)

    class Meta:
        verbose_name = verbose_name_plural = '培養菌株'
        ordering = ['order', 'id']

    def __str__(self):
        return f'{self.organism.name} ({self.growth})'


class SusceptibilityResult(models.Model):
    """One antibiotic line on an isolate's sensitivity panel."""

    class Interpretation(models.TextChoices):
        SUSCEPTIBLE = 'S', '敏感 (S)'
        INTERMEDIATE = 'I', '中等 (I)'
        RESISTANT = 'R', '抗藥 (R)'

    isolate = models.ForeignKey(
        CultureIsolate,
        on_delete=models.CASCADE,
        related_name='susceptibilities',
        verbose_name='培養菌株',
    )
    antibiotic = models.CharField('抗生素', max_length=128)
    mic = models.CharField('MIC', max_length=32, blank=True)
    interpretation = models.CharField(
        '判讀', max_length=1, choices=Interpretation.choices
    )
    order = models.PositiveIntegerField('排序', default=0)

    class Meta:
        verbose_name = verbose_name_plural = '抗生素敏感性'
        ordering = ['order', 'antibiotic']

    def __str__(self):
        return f'{self.antibiotic} {self.interpretation}'


class Tube(models.Model):
    """Catheter / tube master data — the original ``TUBE`` table.

    ``category`` mirrors the original magic numbers, but as named choices:
    1 = the canonical name, 2 and 3 = raw spellings awaiting mapping onto a
    canonical tube via ``canonical``.
    """

    class Category(models.IntegerChoices):
        CANONICAL = 1, '標準名稱'
        VARIANT_A = 2, '待歸類（來源一）'
        VARIANT_B = 3, '待歸類（來源二）'

    tube_no = models.PositiveIntegerField('導管編號', unique=True)
    name = models.CharField('導管名稱', max_length=128)
    category = models.IntegerField('分類', choices=Category.choices)
    canonical = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='variants',
        verbose_name='對應標準名稱',
        limit_choices_to={'category': Category.CANONICAL},
    )
    usage_count = models.PositiveIntegerField('使用次數', default=0)

    class Meta:
        verbose_name = verbose_name_plural = '導管'
        ordering = ['tube_no']

    def __str__(self):
        return f'{self.tube_no} {self.name}'
