# Generated by Django 4.2.30 on 2026-08-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="research.researchtopic",
                        verbose_name="研究主題",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究主題權限",
                "verbose_name_plural": "研究主題權限",
                "ordering": ["user_id", "topic_id"],
            },
        ),
        migrations.CreateModel(
            name="SectionPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[("research", "癌症研究"), ("infection", "感染管控")],
                        max_length=16,
                        verbose_name="功能區塊",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "功能區塊權限",
                "verbose_name_plural": "功能區塊權限",
                "ordering": ["user_id", "section"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=64, verbose_name="姓名"),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=64, verbose_name="單位"),
                ),
                (
                    "de_identification",
                    models.BooleanField(
                        default=True, help_text="開啟時病患姓名以遮罩顯示", verbose_name="去識別化顯示"
                    ),
                ),
                (
                    "can_see_all_reviews",
                    models.BooleanField(default=False, verbose_name="可檢視所有人的標註"),
                ),
                (
                    "can_edit_stage_definition",
                    models.BooleanField(default=False, verbose_name="可編輯階段定義"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={"verbose_name": "使用者設定", "verbose_name_plural": "使用者設定",},
        ),
        migrations.AddConstraint(
            model_name="topicpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "topic"), name="unique_topic_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "section"), name="unique_section_permission"
            ),
        ),
    ]
