# Generated by Django 4.2.30 on 2026-08-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinical", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="疾病名稱"),
                ),
            ],
            options={
                "verbose_name": "疾病分組",
                "verbose_name_plural": "疾病分組",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="主題名稱"),
                ),
                ("description", models.TextField(blank=True, verbose_name="說明")),
            ],
            options={
                "verbose_name": "研究主題",
                "verbose_name_plural": "研究主題",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StageDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="階段名稱")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_definitions",
                        to="research.researchtopic",
                        verbose_name="研究主題",
                    ),
                ),
            ],
            options={
                "verbose_name": "病患階段定義",
                "verbose_name_plural": "病患階段定義",
                "ordering": ["topic_id", "order"],
            },
        ),
        migrations.CreateModel(
            name="StageConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                (
                    "confirmed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="確認時間"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_confirmations",
                        to="clinical.patient",
                        verbose_name="病患",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_confirmations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認者",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="research.stagedefinition",
                        verbose_name="階段",
                    ),
                ),
            ],
            options={
                "verbose_name": "階段確認紀錄",
                "verbose_name_plural": "階段確認紀錄",
                "ordering": ["-confirmed_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="research.diseasegroup",
                        verbose_name="疾病分組",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="clinical.patient",
                        verbose_name="病患",
                    ),
                ),
            ],
            options={"verbose_name": "病患疾病關聯", "verbose_name_plural": "病患疾病關聯",},
        ),
        migrations.CreateModel(
            name="ExamStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_id",
                    models.CharField(db_index=True, max_length=32, verbose_name="檢查編號"),
                ),
                ("series_id", models.CharField(max_length=32, verbose_name="序列編號")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="檢查說明"),
                ),
                (
                    "series_description",
                    models.CharField(blank=True, max_length=255, verbose_name="序列說明"),
                ),
                (
                    "slice_count",
                    models.PositiveIntegerField(default=0, verbose_name="影像張數"),
                ),
                (
                    "hospital",
                    models.CharField(blank=True, max_length=32, verbose_name="院區"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="clinical.clinicalevent",
                        verbose_name="臨床事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "檢查紀錄",
                "verbose_name_plural": "檢查紀錄",
                "ordering": ["study_id", "series_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stagedefinition",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="unique_stage_per_topic"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageconfirmation",
            constraint=models.UniqueConstraint(
                fields=("patient", "stage", "reviewer"),
                name="unique_stage_confirmation",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientdisease",
            constraint=models.UniqueConstraint(
                fields=("patient", "disease"), name="unique_patient_disease"
            ),
        ),
    ]
