# Generated by Django 4.2.30 on 2026-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryPoolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(-1, "已捨棄"), (0, "待確認"), (1, "已確認")],
                        default=0,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "categorized_count",
                    models.PositiveIntegerField(default=0, verbose_name="已歸類次數"),
                ),
            ],
            options={
                "verbose_name": "待歸類字詞",
                "verbose_name_plural": "待歸類字詞",
                "ordering": ["category_id", "token_id"],
            },
        ),
        migrations.CreateModel(
            name="ConversionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="分類名稱")),
                ("pool", models.CharField(max_length=64, verbose_name="所屬詞庫")),
            ],
            options={
                "verbose_name": "歸類分類",
                "verbose_name_plural": "歸類分類",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InfectionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="分類名稱"),
                ),
            ],
            options={
                "verbose_name": "感染分類",
                "verbose_name_plural": "感染分類",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, unique=True, verbose_name="字詞"),
                ),
            ],
            options={
                "verbose_name": "字詞",
                "verbose_name_plural": "字詞",
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="ConversionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="infection.conversioncategory",
                        verbose_name="歸類分類",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_entries",
                        to="infection.token",
                        verbose_name="字詞",
                    ),
                ),
            ],
            options={
                "verbose_name": "已歸類字詞",
                "verbose_name_plural": "已歸類字詞",
                "ordering": ["category_id", "token_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversioncategory",
            constraint=models.UniqueConstraint(
                fields=("name", "pool"), name="unique_conversion_category_per_pool"
            ),
        ),
        migrations.AddField(
            model_name="categorypoolentry",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_entries",
                to="infection.infectioncategory",
                verbose_name="感染分類",
            ),
        ),
        migrations.AddField(
            model_name="categorypoolentry",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pool_entries",
                to="infection.token",
                verbose_name="字詞",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversionentry",
            constraint=models.UniqueConstraint(
                fields=("category", "token"), name="unique_conversion_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorypoolentry",
            constraint=models.UniqueConstraint(
                fields=("category", "token"), name="unique_pool_entry_per_category"
            ),
        ),
    ]
